package com;
import java.util.Calendar;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ComplianceCalculator implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ComplianceCalculator() {
    }
    
    public java.lang.Boolean isMerchantCompliant(java.lang.Boolean hasValidSAQ, java.lang.Boolean isScanObliged, java.lang.Boolean hasProvidedScan){
        java.lang.Boolean isCompliant = false;
        if(hasValidSAQ == true){
            if(isScanObliged == true){
                if(hasProvidedScan == true){
                    isCompliant = true;
                }
            }else{
                isCompliant = true;
            }
        }
        return isCompliant;
    }
    
    public Date calculateComplianceExpirationDate(){
        Calendar cal = Calendar.getInstance();
        Date today = cal.getTime();
        cal.add(Calendar.YEAR, 1); 
        Date nextYearToday = cal.getTime();
        return nextYearToday;
    }
}