package com;
import java.util.Date;
//import org.jbpm.document.service.impl.DocumentImpl;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MerchantDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("CustomerID")
	private java.lang.Integer customerID;
	@org.kie.api.definition.type.Label("Street")
	private java.lang.String street;
	@org.kie.api.definition.type.Label("PostalCode")
	private java.lang.Integer postalCode;
	@org.kie.api.definition.type.Label("City")
	private java.lang.String city;
	@org.kie.api.definition.type.Label("Country")
	private java.lang.String country;

	@org.kie.api.definition.type.Label("VisaCardYearlyCount")
	private java.lang.Integer visaCardYearlyCount;

	@org.kie.api.definition.type.Label("MasterCardYearlyCount")
	private java.lang.Integer masterCardYearlyCount;

	@org.kie.api.definition.type.Label("PCILevel")
	private java.lang.Integer pciLevel;

	@org.kie.api.definition.type.Label("Iscompliance")
	private java.lang.Boolean isCompliance;

	@org.kie.api.definition.type.Label("ComplianceExpirationDate")
	private java.util.Date complianceExpirationDate;

	@org.kie.api.definition.type.Label("StoreSensetiveData")
	private java.lang.Boolean storeSensetiveData;

	@org.kie.api.definition.type.Label("SecureEnvironment")
	private java.lang.Boolean secureEnvironment;

	@org.kie.api.definition.type.Label("NeedScan")
	private java.lang.Boolean needScan;

	@org.kie.api.definition.type.Label("BehindFireWall")
	private java.lang.Boolean behindFireWall;

	@org.kie.api.definition.type.Label("ValidSAQ")
	private java.lang.Boolean hasValidSAQ;

	@org.kie.api.definition.type.Label(value = "ValidExternalSAQ")
	private java.lang.Boolean validExternalSAQ;

	public MerchantDetails() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getCustomerID() {
		return this.customerID;
	}

	public void setCustomerID(java.lang.Integer customerID) {
		this.customerID = customerID;
	}

	public java.lang.String getStreet() {
		return this.street;
	}

	public void setStreet(java.lang.String street) {
		this.street = street;
	}

	public java.lang.Integer getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(java.lang.Integer postalCode) {
		this.postalCode = postalCode;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.Integer getVisaCardYearlyCount() {
		return this.visaCardYearlyCount;
	}

	public void setVisaCardYearlyCount(java.lang.Integer visaCardYearlyCount) {
		this.visaCardYearlyCount = visaCardYearlyCount;
	}

	public java.lang.Integer getMasterCardYearlyCount() {
		return this.masterCardYearlyCount;
	}

	public void setMasterCardYearlyCount(java.lang.Integer masterCardYearlyCount) {
		this.masterCardYearlyCount = masterCardYearlyCount;
	}

	public java.lang.Integer getPciLevel() {
		return this.pciLevel;
	}

	public void setPciLevel(java.lang.Integer pciLevel) {
		this.pciLevel = pciLevel;
	}

	public java.lang.Boolean getIsCompliance() {
		return this.isCompliance;
	}

	public void setIsCompliance(java.lang.Boolean isCompliance) {
		this.isCompliance = isCompliance;
	}

	public Date getComplianceExpirationDate() {
		return this.complianceExpirationDate;
	}

	public void setComplianceExpirationDate(Date complianceExpirationDate) {
		this.complianceExpirationDate = complianceExpirationDate;
	}

	public java.lang.Boolean getStoreSensetiveData() {
		return this.storeSensetiveData;
	}

	public void setStoreSensetiveData(java.lang.Boolean storeSensetiveData) {
		this.storeSensetiveData = storeSensetiveData;
	}

	public java.lang.Boolean getSecureEnvironment() {
		return this.secureEnvironment;
	}

	public void setSecureEnvironment(java.lang.Boolean secureEnvironment) {
		this.secureEnvironment = secureEnvironment;
	}

	public java.lang.Boolean getNeedScan() {
		return this.needScan;
	}

	public void setNeedScan(java.lang.Boolean needScan) {
		this.needScan = needScan;
	}

	public java.lang.Boolean getBehindFireWall() {
		return this.behindFireWall;
	}

	public void setBehindFireWall(java.lang.Boolean behindFireWall) {
		this.behindFireWall = behindFireWall;
	}

	public void isScanObliged(java.lang.Integer pcilevel,
			java.lang.String deliveryStrategy) {

		this.setNeedScan(false);

		if (pcilevel == 1) {
			this.setNeedScan(true);
		}

		else if (deliveryStrategy.equals("external")) {
			this.setNeedScan(true);
		}

	}

	public java.lang.Boolean getHasValidSAQ() {
		return this.hasValidSAQ;
	}

	public void setHasValidSAQ(java.lang.Boolean hasValidSAQ) {
		this.hasValidSAQ = hasValidSAQ;
	}

	public void hasProvidedValidSAQ(java.lang.String deliveryStartegy,
			java.lang.String saqVersion, java.lang.String saqType) {
		if (deliveryStartegy != null && !deliveryStartegy.isEmpty()) {
			if (deliveryStartegy.equals("internal")) {
				if (saqVersion != null && !saqVersion.isEmpty()) {
					if (saqType != null && !saqType.isEmpty()) {
						this.setHasValidSAQ(true);
					}
				}
			} else if (deliveryStartegy.equals("external")) {
			    if(this.getValidExternalSAQ()){
			        this.setHasValidSAQ(true);
			    }

			}

		} else {
			this.setHasValidSAQ(false);
		}
	}

	public void hasValidExternalSAQ(java.lang.Boolean existsFile, java.lang.String name, java.lang.Long fileSize) {
		java.lang.Boolean hasValidExternaSAQ = false;
		if (existsFile && name != null && !name.isEmpty()) {
			if (fileSize != null && ((Long.valueOf(fileSize).doubleValue() / 1000000) > 1)) {
			    hasValidExternaSAQ = true;
			}
		}
		this.setValidExternalSAQ(hasValidExternaSAQ);
	}

	public java.lang.Boolean getValidExternalSAQ() {
		return this.validExternalSAQ;
	}

	public void setValidExternalSAQ(java.lang.Boolean validExternalSAQ) {
		this.validExternalSAQ = validExternalSAQ;
	}

	public MerchantDetails(java.lang.String name, java.lang.Integer customerID,
			java.lang.String street, java.lang.Integer postalCode,
			java.lang.String city, java.lang.String country,
			java.lang.Integer visaCardYearlyCount,
			java.lang.Integer masterCardYearlyCount,
			java.lang.Integer pciLevel, java.lang.Boolean isCompliance,
			java.util.Date complianceExpirationDate,
			java.lang.Boolean storeSensetiveData,
			java.lang.Boolean secureEnvironment, java.lang.Boolean needScan,
			java.lang.Boolean behindFireWall, java.lang.Boolean hasValidSAQ,
			java.lang.Boolean validExternalSAQ) {
		this.name = name;
		this.customerID = customerID;
		this.street = street;
		this.postalCode = postalCode;
		this.city = city;
		this.country = country;
		this.visaCardYearlyCount = visaCardYearlyCount;
		this.masterCardYearlyCount = masterCardYearlyCount;
		this.pciLevel = pciLevel;
		this.isCompliance = isCompliance;
		this.complianceExpirationDate = complianceExpirationDate;
		this.storeSensetiveData = storeSensetiveData;
		this.secureEnvironment = secureEnvironment;
		this.needScan = needScan;
		this.behindFireWall = behindFireWall;
		this.hasValidSAQ = hasValidSAQ;
		this.validExternalSAQ = validExternalSAQ;
	}

}