package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PCIDSS implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("PCIExpirationDate")
	private java.util.Date pciExpirationDate;

	public PCIDSS() {
	}

	public java.util.Date getPciExpirationDate() {
		return this.pciExpirationDate;
	}

	public void setPciExpirationDate(java.util.Date pciExpirationDate) {
		this.pciExpirationDate = pciExpirationDate;
	}

	public java.lang.Integer calculatePCILevel(java.lang.String deliveryStrategy, java.lang.Integer visaYearly, java.lang.Integer mcYearly) {
	    if(deliveryStrategy.equals("external")){
	        return 1;
	    }

		if (visaYearly >= 6000000 || mcYearly >= 6000000) {
			return 1;

		}
		if ((visaYearly < 6000000 && visaYearly >= 1000000)
				|| (mcYearly < 6000000 && mcYearly >= 1000000)) {
			return 2;

		}
		if ((visaYearly < 1000000 && visaYearly >= 20000)
				|| (mcYearly < 1000000 && mcYearly >= 20000)) {
			return 3;

		}if (visaYearly < 20000 || mcYearly < 20000) {
			return 4;

		}
		
		return 1;

	}
	

	public PCIDSS(java.util.Date pciExpirationDate) {
		this.pciExpirationDate = pciExpirationDate;
	}

}
