package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SAQ implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("SAQType")
	private java.lang.String saqType;
	@org.kie.api.definition.type.Label("SAQVersion")
	private java.lang.String saqVersion;

	@org.kie.api.definition.type.Label(value = "DeliveryStrategy")
	private java.lang.String deliveryStrategy;

	public SAQ() {
	}

	public java.lang.String getSaqType() {
		return this.saqType;
	}

	public void setSaqType(java.lang.String saqType) {
		this.saqType = saqType;
	}

	public java.lang.String getSaqVersion() {
		return this.saqVersion;
	}

	public void setSaqVersion(java.lang.String saqVersion) {
		this.saqVersion = saqVersion;
	}

	public void determineSAQType(java.lang.Boolean sensetiveData,
			java.lang.Boolean secureEnvironment,
			java.lang.Boolean behindFireWall, java.lang.String deliveryStrategy) {

        if(deliveryStrategy.equals("external")){
            this.setSaqType("D-Merchant-External");
        }
        
		else if (sensetiveData && secureEnvironment && behindFireWall) {
			this.setSaqType("D-Merchant");
		}

		else if (sensetiveData && secureEnvironment && !behindFireWall) {
			this.setSaqType("A");
		}

		else if (sensetiveData && !secureEnvironment && !behindFireWall) {
			this.setSaqType("B");
		}
		else if (!sensetiveData && secureEnvironment && behindFireWall) {
			this.setSaqType("B-IP");
		} else if (!sensetiveData && !secureEnvironment && behindFireWall) {
			this.setSaqType("B-IP");
		} else {
			this.setSaqType("C");
		}
	}
	
	public java.lang.String getDeliveryStrategy() {
		return this.deliveryStrategy;
	}

	public void setDeliveryStrategy(java.lang.String deliveryStrategy) {
		this.deliveryStrategy = deliveryStrategy;
	}

	public SAQ(java.lang.String saqType, java.lang.String saqVersion,
			java.lang.String deliveryStrategy) {
		this.saqType = saqType;
		this.saqVersion = saqVersion;
		this.deliveryStrategy = deliveryStrategy;
	}

}